### ISSUE TITLE
Typo into README.md

### ISSUE THREAD

**Issue by johuder33** [GuillaumeCisco/redux-reducers-injector#1]
This is not actually an issue, but maybe can be a little confuse, please update your documentation for step 2

right now you have something like 

```javascript
import { createInjectStore } from 'redux-injector';

let store = createInjectStore(
  reducersObject,
  initialState
); 
```

the typo is in the import statement, you should import from your package `redux-reducers-injector` not old or inspired package `redux-injector`

```javascript
import { createInjectStore } from 'redux-reducers-injector';

let store = createInjectStore(
  reducersObject,
  initialState
); 
```

if you need a PR I can help you.

**Comment by GuillaumeCisco** [comment]
Nice catch @johuder33 !
Thanks for pointing this!
I did not know some people where using this lib. Good to know :+1: 
Will update it immediately.
